services:
  - type: web
    name: ecobazaar-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/AkashKeote/Backend-Springboot.git
    branch: main
    region: singapore
    buildFilter:
      paths:
        - src/**
        - pom.xml
        - Dockerfile
        - .mvn/**
        - mvnw
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        value: jdbc:mysql://centerbeam.proxy.rlwy.net:36676/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: cOkdTzTVvUIwNKaGinyHGFGipGhBqYWr
      - key: JWT_SECRET
        value: ecobazaarX2024SecretKeyForJWTTokenGeneration
      - key: CORS_ORIGINS
        value: https://ecobazzarx.web.app/
    healthCheckPath: /healthz